language: php

sudo: false

# whitelist for building branches
branches:
  only:
    - master
    - stable

matrix:
    include:
        - php: 5.6
        - php: 7
        - php: 7.1
    fast_finish: true

before_install:
    - composer self-update

before_script:
    - composer install

script:
    - vendor/bin/phpunit --bootstrap vendor/autoload.php --coverage-clover build/logs/clover.xml tests/

after_success:
  - travis_retry php vendor/bin/coveralls